{% set name = "metanetx-sdk" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33873da6d140c0555c20683c4b330d293f0d39e47a8aae038d47d62109ae68d4

build:
  noarch: python
  entry_points:
    - mnx-sdk = metanetx_sdk.cli.cli:cli
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - aioftp
    - click
    - click-log
    - depinfo
    - pandas
    - pydantic
    - python >=3.8
    - python-dateutil
    - pytz
    - toml

test:
  imports:
    - metanetx_sdk
    - metanetx_sdk.api
  commands:
    - mnx-sdk --help

about:
  home: https://pypi.org/project/metanetx-sdk/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Parse and prepare information from [MetaNetX](https://metanetx.org).
  description: |
    The main purpose of metanetx-sdk is to download and parse the data tables
    provided by the [MetaNetX FTP
    server](ftp://ftp.vital-it.ch/databases/metanetx/MNXref/). The tables can be
    further transformed to replace the database prefixes for identifiers used by
    MetaNetX with [MIRIAM](http://co.mbine.org/standards/miriam) compliant ones
    from [Identifiers.org](http://identifiers.org/).
  doc_url: https://metanetx-sdk.readthedocs.io/
  dev_url: https://github.com/Midnighter/metanetx-sdk

extra:
  recipe-maintainers:
    - Midnighter
